# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
