# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-13 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superlist', '0002_auto_20161031_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
